spring:
  application:
    name: WorldProvider
  data:
    mongodb:
      database: world_provider
      uri: mongodb://root:example@localhost:27017/world_provider?authSource=admin

server:
  port: 9051
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always
    include-stacktrace: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,readyness,readiness

logging:
  level:
    root: INFO
    de.mhus.nimbus: DEBUG
