spring:
  application:
    name: WorldPlayer
  data:
    mongodb:
      database: world
      uri: mongodb://root:example@localhost:27017/world?authSource=admin

world:
  player:
    readiness:
      max-active-sessions: 100
    chunk-publish-interval-ms: 60000  # 1 minute - Periodic chunk list publish interval

server:
  port: 9042
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always
    include-stacktrace: always

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,readyness,readiness

logging:
  level:
    root: INFO
    de.mhus.nimbus: DEBUG
