spring:
  application:
    name: universe
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/universe?authSource=admin
      database: universe

universe:
  security:
    authExpiresMinutes: 15
    refreshExpiresDays: 30

server:
  port: 9040
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO
