spring:
  application:
    name: universe
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/universe?authSource=admin
      database: universe

nimbus:
  encryption:
    password: ${NIMBUS_ENCRYPTION_PASSWORD:changeThisPasswordInProduction}

universe:
  security:
    auth-expires-minutes: 15
    refresh-expires-days: 30

server:
  port: 9040
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    de.mhus.nimbus: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,readyness,readiness
  endpoint:
    health:
      probes:
        enabled: true
