spring:
  application:
    name: universe
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/universe?authSource=admin
      database: universe

# Optional: logging level adjustments
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO
