spring:
  application:
    name: universe
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/universe?authSource=admin
      database: universe

security:
  jwt:
    keyId: system:authkey
    secretBase64: c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0
    expiresMinutes: 60

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO
