spring:
  application:
    name: Region
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/region?authSource=admin
      database: region

region:
  server:
    id: local-region-server
    url: http://localhost:9041
universe:
    url: http://localhost:9040

server:
  port: 9041
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: always

logging:
  level:
    root: INFO
    de.mhus.nimbus: DEBUG

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,readyness,readiness
